export const data = [
    {
        id:1,
        name: 'Brigit Chair',
        url: 'https://images.unsplash.com/photo-1517705008128-361805f42e86?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1279&q=80',
        price: 44.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Living Room',
        sku: 'RHU9211KJ9004',
        brand: 'Ikea',
        freeShipping: true,
        colors: ['white','black']
    },

    {
        id:2,
        name: 'Caspar Armchair',
        url: 'https://images.unsplash.com/photo-1550226891-ef816aed4a98?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
        price: 69.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Living Room',
        sku: 'RHZ3211LJ9004',
        brand: 'Amalia',
        freeShipping: true,
        colors: ['orange','blue']
    },
    {
        id:3,
        name: 'Royal Bed',
        url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80',
        price: 119.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Bedroom',
        sku: 'RTW1671LP9204',
        brand: 'Royal Furniture',
        freeShipping: true,
        colors: ['white','blue']
    },
    {
        id:4,
        name: 'Phaenna Sofa',
        url: 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1353&q=80',
        price: 119.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Living Room',
        sku: 'RKZ6211LP9204',
        brand: 'Ikea',
        freeShipping: true,
        colors: ['white','blue','black']
    },
    {
        id:5,
        name: 'Caspar Barstools',
        url: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
        price: 119.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Kitchen',
        sku: 'ROX7091PY9124',
        brand: 'Amalia',
        freeShipping: true,
        colors: ['white']
    },
    {
        id:6,
        name: 'Svarog Mirror',
        url: 'https://images.unsplash.com/photo-1502921451607-29fa99d270d4?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
        price: 89.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Bedroom',
        sku: 'ROX7091PY9124',
        brand: 'Ferretti',
        freeShipping: true,
        colors: ['white','black']
    },
    {
        id:7,
        name: 'Caspar Sofa',
        url: 'https://images.unsplash.com/photo-1549187774-b4e9b0445b41?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80',
        price: 149.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Living Room',
        sku: 'ROX7091PY9124',
        brand: 'Amalia',
        freeShipping: true,
        colors: ['orange','white','blue']
    },
    {
        id:8,
        name: 'Lolla Desk',
        url: 'https://images.unsplash.com/photo-1531668720450-39cf1563fab9?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1226&q=80',
        price: 99.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Office',
        sku: 'ROX7091PY9124',
        brand: 'Ikea',
        freeShipping: true,
        colors: ['white','black']
    },
    {
        id:9,
        name: 'Office Chair',
        url: 'https://images.unsplash.com/photo-1541558869434-2840d308329a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1349&q=80',
        price: 99.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Office',
        sku: 'ROX7091PY9124',
        brand: 'Ikea',
        freeShipping: true,
        colors: ['blue','black','white']
    },
    {
        id:10,
        name: 'Arnnold Bed',
        url: 'https://images.unsplash.com/photo-1582582621959-48d27397dc69?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
        price: 269.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Bedroom',
        sku: 'ROX7091PY9124',
        brand: 'Royal Furniture',
        freeShipping: true,
        colors: ['white','black','blue']
    },
    {
        id:11,
        name: 'Abstrakt Dinning Table',
        url: 'https://images.unsplash.com/photo-1602872030490-4a484a7b3ba6?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
        price: 109.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Dining',
        sku: 'ROX7091PY9124',
        brand: 'Ferretti',
        freeShipping: true,
        colors: ['white','black','blue']
    },
    {
        id:12,
        name: 'Nuellae Dining Set',
        url: 'https://images.unsplash.com/photo-1570970506581-383d09db285f?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
        price: 389.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Dining',
        sku: 'ROX7091PY9124',
        brand: 'Amalia',
        freeShipping: true,
        colors: ['black','white']
    },
    {
        id:13,
        name: 'Anna Coffee Table',
        url: 'https://images.unsplash.com/photo-1603794067602-9feaa4f70e0c?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
        price: 89.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Living Room',
        sku: 'ROX7091PY9124',
        brand: 'Ikea',
        freeShipping: true,
        colors: ['white','orange']
    },
    {
        id:14,
        name: 'Cornellia Living Room',
        url: 'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80',
        price: 449.99,
        description: ' Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',
        inStock: true,
        type: 'Living Room',
        sku: 'ROX7091PY9124',
        brand: 'Amalia',
        freeShipping: true,
        colors: ['orange','blue','white','black']
    }

]
